#!/usr/bin/env bash
# Displays informtation about subdomains.

# uncomment for debugging purposes
#set -x

# colors
blue='\e[1;34m'
brown='\e[0;33m'
reset='\033[0m'

dig_cmd () {
	# func variables & parameters
	domain="$1"
	sub="$2"
	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "${brown}The subdomain ${blue}$sub${brown} is a ${blue}$RECORD${brown} record and points to ${blue}$IP${reset}"
}

if [ $# -eq 1 ]; then
	subdomains="www lb-01 web-01 web-02"
	for subs in $subdomains; do
		# domain == $1
		dig_cmd "$1" "$subs"
	done
elif [ $# -eq 2 ]; then
	# domain == $1 & subdomain == $2
	dig_cmd "$1" "$2"
fi
