#!/usr/bin/env bash
# Displays informtation about subdomains.

# uncomment for debugging purposes
#set -x

dig_cmd () {
	# func variables & parameters
	sub="$2"
	DOMAIN="$2.$1"
	INFO="$(dig "$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ $# -eq 1 ]; then
	subdomains="www lb-01 web-01 web-02"
	for sub in $subdomains; do
		# domain == $1
		dig_cmd "$1" "$sub"
	done
elif [ $# -eq 2 ]; then
	# domain == $1 & subdomain == $2
	dig_cmd "$1" "$2"
fi
