#!/usr/bin/env bash
# manages manage_my_process by either starting it, stopping it or restarting it.

command="$1"
file="/var/run/myscript.pid"

if [ -z "$command" ]; then

  echo "Usage: manage_my_process {start|stop|restart}"

fi

if [ "$command" == "start" ]; then

  bash ./manage_my_process &
  echo "$!" > "$file"
  echo "manage_my_process started"

elif [ "$command" == "stop" ]; then
  pkill -f manage_my_process
  [ -e "$file" ] && rm "$file"
  echo "manage_my_process stopped"

elif [ "$command" == "restart" ]; then

  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}" 
fi
