#!/usr/bin/env bash
# Tell the story of passwd

file="/etc/passwd"

while IFS= read -r line; do
  user=$(echo "$line" | cut -d ':' -f1)
  gid=$(echo "$line" | cut -d ':' -f4)
  dir=$(echo "$line" | cut -d ':' -f6)
  shell=$(echo "$line" | cut -d ':' -f7)
  uid=$(echo "$line" | cut -d ':' -f3)
  pass=$(echo "$line" | cut -d ':' -f2)
  info=$(echo "$line" | cut -d ':' -f5)

  echo "The user $user is part of the $gid gang, lives in $dir and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < "$file"
