#!/usr/bin/env bash
# prints a string 10 times using while loop and on the ninth iteration it prints hi

i=1

while [ "$i" -lt 11 ]; do
  echo "Best School"
  
  # if statement to print Hi when i is 9
  if [ "$i" -eq 9 ]; then
    echo "Hi"
  fi

  ((i++))
done
