#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

i=1

while [ "$i" -lt 11 ]; do

  # if 4 bad luck elif 8 good luck
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((i++))
done
